ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "appointmentSlotGapMinutes" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "appointmentSlotDurationMinutes" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "appointmentBookingStart" TEXT NOT NULL DEFAULT '09:00';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "appointmentBookingEnd" TEXT NOT NULL DEFAULT '18:00';
