ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "sellerAlertsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "sellerAlertOnInquiry" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "sellerAlertOnChat" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "sellerAlertOnNewOrder" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "sellerAlertOnLowStock" BOOLEAN NOT NULL DEFAULT true;
