import type { CustomerLocale } from "@/lib/customer-preferences";

const EN = {
  home: "Home",
  navProducts: "Products",
  settings: "Settings",
  dashboard: "Dashboard",
  storeActions: "Store actions",
  storeActionsSub: "Buy, order, and contact the store",
  backToActions: "Back to actions",
  dashboardCartHint: "Items in your cart",
  dashboardItems: "items",
  languageSub: "Language & display mode",
  deals: "Deals",
  orders: "Orders",
  menu: "Menu",
  buy: "Shop",
  buyNow: "Shop now",
  inquiries: "Message seller",
  inquiriesSub: "Questions & requests to the store",
  contact: "Contact us",
  contactSeller: "Contact seller",
  store: "Store",
  faqQuick: "Q&A",
  faq: "FAQ",
  faqSub: "Quick answers",
  language: "Language & display",
  legal: "Accessibility & legal",
  legalSub: "Text size, privacy & terms",
  signIn: "Customer sign-in",
  signInSub: "Stored securely with the business",
  noServices: "No services listed yet.",
  noDeals: "No active deals",
  redeemDeal: "Redeem deal",
  dealRedeemed: "Redeemed",
  dealOnce: "One-time per phone number",
  dealValidUntil: "Valid until",
  dealIncludes: "Includes",
  activeOrders: "Active orders",
  cartEmpty: "Cart is empty",
  orderHistory: "Order history",
  comingSoon: "Coming soon",
  deviceDataNote:
    "Orders, appointments and customer details are stored securely with the business owner — not only on your device.",
  orderDetails: "Order details",
  orderAgain: "Order again",
  noPastOrders: "No past orders",
  noSlots: "No appointments available.",
  noMyAppts: "No past appointments",
  appointmentHistory: "Appointment history",
  myAppointments: "My appointments",
  appointments: "Appointments",
  hello: "Hello!",
  helloStoreName: (name: string) => name,
  scheduleAppointment: "Book appointment",
  scheduleRental: "Book rental",
  rentalBookingTitle: "Book rental",
  rentalCheckIn: "Check-in",
  rentalCheckOut: "Check-out",
  rentalPeriod: "Rental period",
  rentalNight: "night",
  rentalNights: "nights",
  rentalDay: "day",
  rentalDays: "days",
  confirmRentalBooking: "Confirm rental",
  rentalBookedTitle: "Rental booked!",
  rentalBookedDetail: "Your rental appears under Orders. Cancellation follows store policy.",
  myRentals: "My rentals",
  rentalHistory: "Rental history",
  noActiveRentals: "No upcoming rentals",
  calendarPickCheckIn: "Pick check-in date",
  openCalendar: "Open calendar",
  calendarPickDay: "Choose a day",
  calendarPickDaySub:
    "Pick a day on the calendar — available, full, and past times appear below.",
  calendarPickTime: "Choose a time",
  calendarNoSlotsDay: "No slots on this day",
  calendarDayViewTitle: "Appointments on this day",
  calendarDayAllSlots: "All times on this day",
  calendarSlotFull: "Fully booked",
  calendarSlotPast: "Past",
  calendarSlotAvailable: "Available",
  calendarSpotsLeft: "left",
  calendarPrevMonth: "Previous month",
  calendarNextMonth: "Next month",
  calendarDayFullHint: "Red = fully booked",
  calendarDayFullTitle: "No openings",
  calendarDayFullMessage:
    "All appointments on this day are taken. Turn on a reminder and we'll notify you if a slot opens.",
  calendarDayClosedHint: "Store closed on this day",
  upcomingOpenSlots: "Upcoming open slots",
  noUpcomingOpenSlots: "No open slots right now",
  appointmentToday: "Today",
  appointmentTomorrow: "Tomorrow",
  appointmentReminderTitle: "Notify when a slot opens",
  appointmentReminderSub: "We'll let you know if a spot opens on a full day",
  appointmentReminderActive: "Reminder on — we'll notify you when a slot opens",
  appointmentReminderEnableButton: "Enable slot notifications",
  bookingTitle: "Book appointment",
  confirmBooking: "Confirm booking",
  bookingSubmitting: "Booking…",
  appointmentBookedTitle: "Appointment booked!",
  appointmentBookedDetail: "Your appointment appears under Orders. You can cancel per store policy.",
  service: "Service",
  cancelAppointment: "Cancel appointment",
  cancelAppointmentBlocked: "Cannot cancel — contact the store",
  noActiveAppts: "No upcoming appointments",
  appointmentPending: "Awaiting confirmation",
  appointmentConfirmed: "Confirmed",
  appointmentCancelled: "Cancelled",
  close: "Close",
  send: "Send",
  name: "Name",
  phone: "Phone",
  message: "Message",
  yourName: "Your name",
  yourPhone: "Phone number",
  invalidPhone: "Enter a valid Israeli mobile number (e.g. 050-1234567)",
  saveMe: "Save me",
  profileSaved: "Saved with the store",
  productInfo: "Product details",
  confirmOrder: "Confirm order",
  completeOrder: "Complete purchase",
  cancelOrder: "Cancel",
  pendingOrder: "Awaiting confirmation",
  orderCheckoutTitle: "Complete your order",
  orderSuccessTitle: "Order sent successfully!",
  orderSuccessDetail: "The store received your order and will prepare it soon.",
  great: "Great",
  book: "Book",
  notes: "Notes",
  total: "Total",
  unavailable: "This business is currently unavailable.",
  outOfStock: "Out of stock",
  sellerNoticeTitle: "Message from the store",
  sellerNoticeTab: "Notice",
  sellerNoticeGotIt: "Got it",
  yourInquiries: "Your messages",
  sellerReplyLabel: "Store reply",
  awaitingReply: "Waiting for reply",
  inquirySent: "Your message was sent",
  inquirySentTitle: "Message sent successfully",
  inquirySentDetail: "The store will get back to you soon.",
  inquiryPendingBlocked:
    "You already have a message waiting for a reply. You can send another after the store responds.",
  yourPastInquiries: "Previous messages",
  inquirySubmitError: "Could not send your message. Please try again.",
  back: "Back",
  contactOptionWhatsApp: "Contact on WhatsApp",
  contactOptionWhatsAppSub: "Message the store directly on WhatsApp",
  contactOptionWhatsAppUnavailable: "WhatsApp contact is not available yet",
  contactOptionPaused: "Temporarily unavailable",
  contactMenuChat: "Chat",
  contactMenuInquiries: "Inquiries",
  contactOptionInquiry: "Contact form",
  contactOptionInquirySub: "Subject and details — the store will reply",
  contactOptionSellerChat: "Chat with seller",
  contactOptionSellerChatSub: "Message the store; they reply when they can",
  historySuspended: "Order history is available for 24 hours after each order",
  historySuspendedShort: "History paused",
  contactOptionCommunity: "Community chat",
  contactOptionCommunitySub: "Chat with other customers and get advice",
  inquirySubject: "Subject",
  inquiryDetails: "Details",
  chatPlaceholder: "Write a message…",
  chatEmpty: "No messages yet. Say hello!",
  chatLoading: "Loading…",
  chatLoadError: "Could not load messages",
  chatSendError: "Could not send message",
  chatPhoneRequired: "Add your phone in customer sign-in first",
  chatNameRequired: "Add your name in customer sign-in first",
  chatSignInToReply: "Sign in to send messages in community chat",
  chatSignInButton: "Sign in",
  phoneVerifyIntro:
    "Verify your phone with a one-time code to view your messages and updates.",
  phoneVerifySend: "Send verification code",
  phoneVerifySending: "Sending…",
  phoneVerifyConfirm: "Verify code",
  phoneVerifyConfirming: "Verifying…",
  phoneVerifyResend: "Resend code",
  phoneVerifyCodePlaceholder: "6-digit code",
  phoneVerifyCodeRequired: "Enter the verification code",
  phoneVerifySendError: "Could not send verification code",
  phoneVerifyError: "Invalid or expired code",
  resolutionQuestion: "Was your issue resolved?",
  resolutionYes: "Yes, resolved",
  resolutionNo: "Not yet",
  resolutionThanksResolved: "Thanks — glad we could help!",
  resolutionThanksNotResolved:
    "Thanks — you can send another message if you need more help.",
  resolutionSubmitError: "Could not save your feedback. Please try again.",
  chatReply: "Reply",
  chatLike: "Like",
  replyingTo: "Replying to",
  cancelReply: "Cancel reply",
  installApp: "Install app",
  installAppSub: "Quick access to this store from your home screen",
  installAppPanelTitle: "Install on your device",
  installAppInstalledTitle: "Store installed",
  installAppInstalledHint: "Open the store anytime from your home screen.",
  installAppButton: "Install",
  installAppIosStep1: "Tap Share at the bottom of Safari",
  installAppIosStep2: "Choose “Add to Home Screen”",
  installAppIosStep3: "Confirm — the store icon will appear on your home screen",
  installAppAndroidHint:
    "In Chrome: menu → “Install app” or “Add to Home screen”.",
  installAppDesktopHint: "On desktop: use the install icon in Chrome or Edge.",
};

const HE: typeof EN = {
  home: "בית",
  navProducts: "מוצרים",
  settings: "הגדרות",
  dashboard: "דאשבורד",
  storeActions: "פעולות בחנות",
  storeActionsSub: "קנייה, הזמנה ופניות לבעל העסק",
  backToActions: "חזרה לפעולות",
  dashboardCartHint: "פריטים בעגלה",
  dashboardItems: "פריטים",
  languageSub: "שפה ומצב תצוגה",
  deals: "מבצעים",
  orders: "הזמנות",
  menu: "תפריט",
  buy: "קנייה",
  buyNow: "לקנות",
  inquiries: "פניות למוכר",
  inquiriesSub: "שאלות ובקשות לבעל העסק",
  contact: "צור קשר",
  contactSeller: "פנייה למוכר",
  store: "חנות",
  faqQuick: "שאלות ותשובות",
  faq: "שאלות נפוצות",
  faqSub: "תשובות מהירות",
  language: "שפה ומצב תצוגה",
  legal: "נגישות ומשפטי",
  legalSub: "גודל טקסט, פרטיות ותנאים",
  signIn: "התחברות לקוח",
  signInSub: "נשמר בצורה מאובטחת אצל בעל העסק",
  noServices: "אין שירותים ברשימה עדיין.",
  noDeals: "אין מבצעים פעילים",
  redeemDeal: "ממש דיל",
  dealRedeemed: "מומש",
  dealOnce: "פעם אחת לכל מספר טלפון",
  dealValidUntil: "בתוקף עד",
  dealIncludes: "כולל",
  activeOrders: "הזמנות פעילות",
  cartEmpty: "העגלה ריקה",
  orderHistory: "היסטוריית הזמנות",
  comingSoon: "בקרוב",
  deviceDataNote:
    "הזמנות, תורים ופרטי לקוח נשמרים בצורה מאובטחת אצל בעל העסק — לא רק במכשיר שלך.",
  orderDetails: "פרטי הזמנה",
  orderAgain: "הזמן שוב",
  noPastOrders: "אין הזמנות קודמות",
  noSlots: "אין תורים זמינים.",
  noMyAppts: "אין תורים קודמים",
  appointmentHistory: "היסטוריית תורים",
  myAppointments: "התורים שלי",
  appointments: "תורים",
  hello: "שלום!",
  helloStoreName: (name: string) => name,
  scheduleAppointment: "לקביעת תור",
  scheduleRental: "להזמנת השכרה",
  rentalBookingTitle: "הזמנת השכרה",
  rentalCheckIn: "כניסה",
  rentalCheckOut: "יציאה",
  rentalPeriod: "תקופת השכרה",
  rentalNight: "לילה",
  rentalNights: "לילות",
  rentalDay: "יום",
  rentalDays: "ימים",
  confirmRentalBooking: "אישור השכרה",
  rentalBookedTitle: "ההשכרה נקבעה!",
  rentalBookedDetail: "ההשכרה מופיעה בלשונית הזמנות. ניתן לבטל לפי מדיניות החנות.",
  myRentals: "ההשכרות שלי",
  rentalHistory: "היסטוריית השכרות",
  noActiveRentals: "אין השכרות קרובות",
  calendarPickCheckIn: "בחרו תאריך כניסה",
  openCalendar: "פתח יומן",
  calendarPickDay: "בחרו יום",
  calendarPickDaySub:
    "בחרו יום ביומן — למטה יוצגו כל השעות: פנויות, תפוסות ושעות שעברו.",
  calendarPickTime: "בחרו שעה",
  calendarNoSlotsDay: "אין תורים ביום זה",
  calendarDayViewTitle: "תורים ביום",
  calendarDayAllSlots: "כל השעות ביום",
  calendarSlotFull: "תפוס",
  calendarSlotPast: "עבר",
  calendarSlotAvailable: "פנוי",
  calendarSpotsLeft: "פנויים",
  calendarPrevMonth: "חודש קודם",
  calendarNextMonth: "חודש הבא",
  calendarDayFullHint: "אדום = כל התורים נתפסו",
  calendarDayFullTitle: "אין תורים פנויים",
  calendarDayFullMessage:
    "כל התורים באותו היום תפוסים. אפשר להפעיל תזכורת ונודיע לך אם יתפנה תור.",
  calendarDayClosedHint: "החנות סגורה ביום זה",
  upcomingOpenSlots: "תורים קרובים פנויים",
  noUpcomingOpenSlots: "אין תורים פנויים כרגע",
  appointmentToday: "היום",
  appointmentTomorrow: "מחר",
  appointmentReminderTitle: "תזכורת כשיתפנה תור",
  appointmentReminderSub: "נודיע לך אם יתפנה מקום ביום תפוס",
  appointmentReminderActive: "התזכורת פעילה — נודיע כשיתפנה תור",
  appointmentReminderEnableButton: "הפעל התראות כשיתפנה תור",
  bookingTitle: "קביעת תור",
  confirmBooking: "אישור קביעה",
  bookingSubmitting: "קובעים…",
  appointmentBookedTitle: "התור נקבע!",
  appointmentBookedDetail: "התור מופיע בלשונית הזמנות. ניתן לבטל לפי מדיניות החנות.",
  service: "שירות",
  cancelAppointment: "ביטול תור",
  cancelAppointmentBlocked: "לא ניתן לבטל — פנו לחנות",
  noActiveAppts: "אין תורים קרובים",
  appointmentPending: "ממתין לאישור",
  appointmentConfirmed: "אושר",
  appointmentCancelled: "בוטל",
  close: "סגור",
  send: "שליחה",
  name: "שם",
  phone: "טלפון",
  message: "הודעה",
  yourName: "השם שלך",
  yourPhone: "מספר טלפון",
  invalidPhone: "יש להזין מספר נייד ישראלי תקין (למשל 050-1234567)",
  saveMe: "שמור אותי",
  profileSaved: "נשמר אצל החנות",
  productInfo: "מידע על המוצר",
  confirmOrder: "אישור ההזמנה",
  completeOrder: "השלמת קניה",
  cancelOrder: "ביטול",
  pendingOrder: "ממתין לאישור",
  orderCheckoutTitle: "פרטים להשלמת ההזמנה",
  orderSuccessTitle: "ההזמנה הושלמה בהצלחה!",
  orderSuccessDetail: "החנות קיבלה את ההזמנה ותתחיל בהכנה.",
  great: "מעולה",
  book: "הזמן",
  notes: "הערות",
  total: 'סה"כ',
  unavailable: "העסק אינו זמין כרגע.",
  outOfStock: "אזל מהמלאי",
  sellerNoticeTitle: "הודעה מהמוכר",
  sellerNoticeTab: "הודעה",
  sellerNoticeGotIt: "הבנתי",
  yourInquiries: "הפניות שלי",
  sellerReplyLabel: "תשובת החנות",
  awaitingReply: "ממתין לתשובה",
  inquirySent: "הפנייה נשלחה",
  inquirySentTitle: "הפנייה נשלחה בהצלחה",
  inquirySentDetail: "המוכר יחזור אליך בהקדם האפשרי.",
  inquiryPendingBlocked:
    "כבר יש לך פנייה שממתינה לתשובה. אפשר לשלוח פנייה חדשה אחרי שתקבל מענה.",
  yourPastInquiries: "פניות קודמות",
  inquirySubmitError: "לא הצלחנו לשלוח את הפנייה. נסה שוב.",
  back: "חזרה",
  contactOptionWhatsApp: "יצירת קשר בוואטסאפ",
  contactOptionWhatsAppSub: "שליחת הודעה ישירה למוכר בוואטסאפ",
  contactOptionWhatsAppUnavailable: "יצירת קשר בוואטסאפ אינה זמינה כרגע",
  contactOptionPaused: "לא זמין כרגע",
  contactMenuChat: "צ'אט",
  contactMenuInquiries: "פניות",
  contactOptionInquiry: "פנייה",
  contactOptionInquirySub: "נושא ופירוט — החנות תחזור אליך",
  contactOptionSellerChat: "צ'אט עם המוכר",
  contactOptionSellerChatSub: "התכתבות עם החנות; המוכר יענה כשיוכל",
  historySuspended:
    "היסטוריית הזמנות זמינה ל-24 שעות בלבד לאחר כל הזמנה",
  historySuspendedShort: "ההיסטוריה מושהית",
  contactOptionCommunity: "צ'אט קהילתי",
  contactOptionCommunitySub: "התייעצות עם לקוחות אחרים בחנות",
  inquirySubject: "נושא",
  inquiryDetails: "פירוט הפנייה",
  chatPlaceholder: "כתוב הודעה…",
  chatEmpty: "עדיין אין הודעות. אפשר להתחיל!",
  chatLoading: "טוען…",
  chatLoadError: "לא ניתן לטעון הודעות",
  chatSendError: "לא ניתן לשלוח הודעה",
  chatPhoneRequired: "הוסף מספר טלפון בהתחברות לקוח",
  chatNameRequired: "הוסף שם בהתחברות לקוח",
  chatSignInToReply: "כדי להגיב בצ'אט הקהילתי יש להתחבר",
  chatSignInButton: "התחברות",
  phoneVerifyIntro:
    "לאימות הטלפון נשלח קוד חד-פעמי — כך נוכל להציג את ההודעות והעדכונים שלך בלבד.",
  phoneVerifySend: "שליחת קוד אימות",
  phoneVerifySending: "שולח…",
  phoneVerifyConfirm: "אימות קוד",
  phoneVerifyConfirming: "מאמת…",
  phoneVerifyResend: "שליחה מחדש",
  phoneVerifyCodePlaceholder: "קוד בן 6 ספרות",
  phoneVerifyCodeRequired: "הזינו את קוד האימות",
  phoneVerifySendError: "לא ניתן לשלוח קוד אימות",
  phoneVerifyError: "קוד שגוי או שפג תוקפו",
  resolutionQuestion: "האם הבעיה נפתרה?",
  resolutionYes: "כן, נפתרה",
  resolutionNo: "לא, עדיין לא",
  resolutionThanksResolved: "תודה — שמחים שעזרנו!",
  resolutionThanksNotResolved:
    "תודה — אפשר לשלוח הודעה נוספת אם צריך עזרה נוספת.",
  resolutionSubmitError: "לא ניתן לשמור את המשוב. נסו שוב.",
  chatReply: "הגב",
  chatLike: "לייק",
  replyingTo: "תגובה ל",
  cancelReply: "ביטול תגובה",
  installApp: "התקנת אפליקציה",
  installAppSub: "גישה מהירה לחנות מהמסך הראשי",
  installAppPanelTitle: "התקנה במכשיר",
  installAppInstalledTitle: "החנות מותקנת",
  installAppInstalledHint: "אפשר לפתוח את החנות מהמסך הראשי בכל עת.",
  installAppButton: "התקנה",
  installAppIosStep1: "לחצו על כפתור השיתוף בתחתית Safari",
  installAppIosStep2: "בחרו «הוספה למסך הבית»",
  installAppIosStep3: "אשרו — אייקון החנות יופיע במסך הבית",
  installAppAndroidHint:
    "ב-Chrome: תפריט → «התקן אפליקציה» או «הוסף למסך הבית».",
  installAppDesktopHint: "במחשב: אייקון ההתקנה ב-Chrome או Edge.",
};

export function getCustomerLabels(locale: CustomerLocale) {
  return locale === "he" ? HE : EN;
}

export type CustomerLabels = typeof EN;
