import type { CustomerLocale } from "@/lib/customer-preferences";

const EN = {
  settings: "Settings",
  dashboard: "Dashboard",
  storeActions: "Store actions",
  storeActionsSub: "Buy, order, and contact the store",
  backToActions: "Back to actions",
  dashboardCartHint: "Items in your cart",
  dashboardItems: "items",
  languageSub: "Language & display mode",
  deals: "Deals",
  orders: "Orders",
  menu: "Menu",
  buy: "Shop",
  buyNow: "Shop now",
  inquiries: "Message seller",
  inquiriesSub: "Questions & requests to the store",
  contact: "Contact us",
  contactSeller: "Contact seller",
  store: "Store",
  faqQuick: "Q&A",
  faq: "FAQ",
  faqSub: "Quick answers",
  language: "Language & display",
  legal: "Accessibility & legal",
  legalSub: "Text size, privacy & terms",
  signIn: "Customer sign-in",
  signInSub: "Saved on this device",
  noServices: "No services listed yet.",
  noDeals: "No active deals",
  redeemDeal: "Redeem deal",
  dealOnce: "One-time per phone number",
  dealValidUntil: "Valid until",
  dealIncludes: "Includes",
  activeOrders: "Active orders",
  cartEmpty: "Cart is empty",
  orderHistory: "Order history",
  noPastOrders: "No past orders",
  noSlots: "No appointments available.",
  noMyAppts: "No past appointments",
  myAppointments: "My appointments",
  appointments: "Appointments",
  close: "Close",
  send: "Send",
  name: "Name",
  phone: "Phone",
  message: "Message",
  yourName: "Your name",
  confirmOrder: "Confirm order",
  orderCheckoutTitle: "Complete your order",
  orderSuccessTitle: "Order confirmed!",
  orderSuccessDetail: "The store received your order and will prepare it soon.",
  great: "Great",
  book: "Book",
  notes: "Notes",
  total: "Total",
  unavailable: "This business is currently unavailable.",
};

const HE: typeof EN = {
  settings: "הגדרות",
  dashboard: "דאשבורד",
  storeActions: "פעולות בחנות",
  storeActionsSub: "קנייה, הזמנה ופניות לבעל העסק",
  backToActions: "חזרה לפעולות",
  dashboardCartHint: "פריטים בעגלה",
  dashboardItems: "פריטים",
  languageSub: "שפה ומצב תצוגה",
  deals: "מבצעים",
  orders: "הזמנות",
  menu: "תפריט",
  buy: "קנייה",
  buyNow: "לקנות",
  inquiries: "פניות למוכר",
  inquiriesSub: "שאלות ובקשות לבעל העסק",
  contact: "צור קשר",
  contactSeller: "פנייה למוכר",
  store: "חנות",
  faqQuick: "שאלות ותשובות",
  faq: "שאלות נפוצות",
  faqSub: "תשובות מהירות",
  language: "שפה ומצב תצוגה",
  legal: "נגישות ומשפטי",
  legalSub: "גודל טקסט, פרטיות ותנאים",
  signIn: "התחברות לקוח",
  signInSub: "נשמר במכשיר זה",
  noServices: "אין שירותים ברשימה עדיין.",
  noDeals: "אין מבצעים פעילים",
  redeemDeal: "ממש דיל",
  dealOnce: "פעם אחת לכל מספר טלפון",
  dealValidUntil: "בתוקף עד",
  dealIncludes: "כולל",
  activeOrders: "הזמנות פעילות",
  cartEmpty: "העגלה ריקה",
  orderHistory: "היסטוריית הזמנות",
  noPastOrders: "אין הזמנות קודמות",
  noSlots: "אין תורים זמינים.",
  noMyAppts: "אין תורים קודמים",
  myAppointments: "התורים שלי",
  appointments: "תורים",
  close: "סגור",
  send: "שליחה",
  name: "שם",
  phone: "טלפון",
  message: "הודעה",
  yourName: "השם שלך",
  confirmOrder: "אישור הזמנה",
  orderCheckoutTitle: "פרטים להשלמת ההזמנה",
  orderSuccessTitle: "ההזמנה אושרה בהצלחה!",
  orderSuccessDetail: "החנות קיבלה את ההזמנה ותתחיל בהכנה.",
  great: "מעולה",
  book: "הזמן",
  notes: "הערות",
  total: 'סה"כ',
  unavailable: "העסק אינו זמין כרגע.",
};

export function getCustomerLabels(locale: CustomerLocale) {
  return locale === "he" ? HE : EN;
}

export type CustomerLabels = typeof EN;
